const arrNumber1 =[
    {},

    {
        anxious : "xavotirlangan",
        // awful : "juda yomon",
        consist : "iborat bo'lmoq",
        desire : "xoxlamoq",
        eager : "chanqoq, sabrsiz",
        household : "oila a'zolar",
        intent : "maqsad, niyat",
        landscape :" landshaft, manzara",
        lift : "ko'tarmoq",
        load : "yuklamoq",
        lung : "o'pka",
        motion : "harakat",
        // pace : "temp, sur'at",
        polite :" muloyim, odobli",
        possess : "egalik qilmoq",
        rapidly : "juda tez",
        remark : "ta'kidlamoq",
        seek :" qidirmoq",
        shine : "nur taratmoq",
        spill : "to'kib yubormoq",
         
    },
    {
        bring : "olib kelmoq",
        castle : "qasr",
        command : "buyruq bermoq",
        // counsel : "maslahat bermoq",
        ensure : "taminlamoq",
        explosion :" portlash",
        jewelry : "taqinchoq",
        land : "qo'nmoq",
        meteor :" metiorit",
        monster : "mahluq",
        northern : "shimoliy",
        remote : "olis, uzoq , masofaviy",
        southern : "janubiy",
        statue : "haykal",
        steam : "par, bug'",
        submit : "bo'ysunmoq",
        temple : "ibodatxona",
        upper : "yuqori",
        weed : "begona o't",
        wing : "qanot",
    },
    {
        arrow : "o'q, yoy",
        battle : "urush",
        // bow : "kamon",
        brave : "qo'rqmas, jasur",
        chief : "boshliq, sardor",
        disadvantage : "kamchilik",
        enemy : "dushman",
        entrance : "kirish yo'li",
        hardly : "arang, zo'rg'a",
        intend : "niyat qilmoq",
        // laugher : "kulgi, shodlik",
        // log : "jurnal",
        military : "armiya",
        obey :" bo'ysunmoq",
        secure : "qo'lga kiritmoq",
        steady : "barqaror",
        trust : "ishonmoq",
        twist : "aylantirib bog'lamoq",
        unless : "magan taqdirda",
        weapon : "qurol-yarog'"
        
        
    },
    {
        chest : "ko'krak qafasi",
        confidence : "ishonch",
        consequence : "natija, oqibat",
        disaster : "falokat",
     
        estimate : "taxminan baholamoq",
        honor : "sharaflamoq",
        impress : "lol qoldirmoq",
        marathon : "marafon",
        narrow : "tor",
        pale : "xira",
        rough : "qo'pol",
        satisfy : "qoniqtirmoq",
        scream : "baqirmoq",
        sensitive : "ta'sirchan",
        shade : "soya",
        supplement : "qo'shmoq",
        terror : "qo'rquv",
        threat : "xavf, xatar",
        victim : "qurbon",
    },
    {
        ancestor : "ajdod",
        angle : "tomon, burchak",
        boot : "etik",
        border : "chegara",
        congratulate : "tabriklamoq",
        frame : "ramka",
        heaven : "jannat",
        incredible : "aqlga sig'mas",
        legend : "afsona",
        praise : "maqtamoq",
        proceed : "maqsad",
        pure : "sof, musaffo",
        relative : "qarindosh",
        senior : "katta yoshdagi",
        silent : "tinch",
        // sink : "cho'kmoq",
        superior : "yuqori",
        surround :" o'rab olmoq",
        thick : "qalin",
        wrap : "o'ramoq"
    },
    {
        abroad : "xorij, chet",
        anger : "jahlini chiqarmoq",
        bride : "kelinchak",
        brief : "qisqa",
        chase : "quvlamoq",
        disappoint : "hafa qilmoq",
        dive : "suvga sakramoq",
        exchange : "ayriboshlamoq",
        favor : "yordam",
        fee : "to'lov, badal",
        forever : "abadiy",
        guy : "erkak kishi",
        lovely : "yoqimli, go'zal",
        mood : "kayfiyat",
        palace : "qasr, saroy",
        permit : "ruxsat bermoq",
        protest : "norozilik bildirmoq",
        sculpture : "haykal",
        tribe : "qabila",
        youth : "yoshlik payt",
    },
    {
        basis : "asos",
        biology : "biologiya",
        case : "qafas",
        colleague : "hamkasb",
        colony : "kaloniya",
        debate :" muhokama qilmoq",
        depart : "jo'nab ketmoq",
        // depress : "hafa qilmoq",
        factual : "asosli, dalilga boy",
        fascinate : "maftun qilmoq",
        mission : "topshiriq",
        nevertheless : "shunga qaramay",
        occupation : "kasb",
        overseas : "okean orti",
        persuade : "ko'ndirmoq",
        route : "yo'nalish",
        ruins : "xaroba",
        scholar : "bilimdon",
        significant : "muhim",
        volcano : "vulqon",
    },
    {
        broad : "keng, katta",
        bush : "buta",
        capable : "qobiliyatli",
        cheat : "g'irromlik qilmoq",
        concentrate : "diqqatni jamlamoq",
        conclude :" deb xulosa qilmoq",
        confident : "o'ziga ishongan",
        considerably : "sezilarli",
        convey : "ifodalamoq",
        definite : "aniq, yaqqol",
        delight : "zavq, shavq",
        destination : "manzil",
        dictate : "aytib yozdirmoq",
        edge : "chet, qirra",
        path : "yo'l",
        resort : "asoslanmoq",
        shadow : "soya",
        succeed : "muvaffaqiyat qozonmoq",
        suspect : "deb hisoblamoq",
        valley : "vodiy",
        
    },
    {
        admire : "qoyil qolmoq",
        // aid : "yordam bermoq",
        attempt :" harakat qilmoq",
        authority : "vakolat, huquq",
        capital : "poytaxt",
        cooperate : "hamkorlik qilmoq",
        defend : "mudofaa qilmoq",
        destruction : "vayrona",
        disorder : "tartibsizlik",
        division : "bo'lish",
        enable : "imkoniyat bermoq",
        frustrate : "umidsizlantirmoq",
        govern : "boshqarmoq",
        plenty : "yetarli miqdor",
        relieve : "yengillashtirmoq",
        reputation : "obro'",
        royal : "qirollik",
        slave : "qul",
        struggle : "kurashmoq",
        stupid : "ahmoq",
    },
    {
        citizen : "fuqaro",
        council : "kengash, konsullik",
        declare : "aytmoq, bildirmoq",
        enourmous : "ulkan",
        extraordinary : "g'ayritabiiy",
        fog : "tuman",
        funeral : "dafn marosimi",
        giant : "ulkan, bahaybat",
        imperession : "taassurot",
        income : "daromad",
        mad : "badjahil",
        ought : "kerak, lozim",
        resist : "qarshilik ko'rsatmoq",
        reveal : "ko'rsatmoq",
        rid : "xalos qilmoq",
        sword : "qilich",
        tale : "ertak",
        trap : "tutqunlikda saqlamoq",
        trial : "sud jarayoni",
        violent : "zo'ravon, quturgan"
    },
    {
        admission :" ruxsat, kirish",
        astronomy : "astonomiya",
        blame : "ayblamoq",
        chemistry : "kimyo",
        despite : "ga qaramasdan",
        dinosaur : "dinozavr",
        exhibit : "eksponat, ko'rgazma",
        fame : "shon-shuhrat, obro",
        forecast : "ob-havo ma'lumoti",
        genius : "juda aqlli",
        gentle : "muloyim, yuvosh",
        geography : "geografiya",
        interfere : "halaqit bermoq",
        lightly : "muloyimlik bilan",
        principal : "maktab direktori",
        row : "qator",
        shelf : "tokcha",
        spite : "qasddan, ataylab",
        super : "juda yaxshi",
        wet : "nam, ho'l",
    },
    {
        abuse : "haqorat qilmoq",
        afford : "qurbi yetmoq",
        bake : "pishirmoq",
        bean : "noxat, loviya",
        candle : "sham",
        convert : "ga aylantirmoq",
        debt : "qarz",
        decrease : "kamaytirmoq",
        fault : "xato, ayb",
        fund : "fond",
        generous : "sahiy, qo'li ochiq",
        ingredient : "tarkibiy qism",
        insist : "talab qilmoq",
        mess :" kir, tartibsizlik",
        metal : "metal, temir",
        monitor :" kuzatib bormoq",
        oppose : "qarshi chiqmoq",
        passive :" passiv, sust",
        quantity : "miqdor",
        sue : "sudga bermoq",
    },
    {
        anxiety : "tashvish, g'am",
        army : "armiya",
        billion : "milliard",
        carve : "kesmoq, tog'ramoq",
        consult : "yordam so'ramoq",
        emergency : "favqulodda vaziyat",
        fortune : "omad",
        guarantee : "kafolat bermoq",
        hike : "piyoda yurmoq",
        initial : "birinchi, dastlabki",
        intense : "jadal",
        peak : "cho'qqi",
        lend : "berib turmoq",
        potential : "ehtimoliy, potensial",
        pride : "mamnuniyat",
        proof : "isbot, dalil",
        quit : "to'xtamoq",
        spin : "aylanmoq",
        tiny : "kichik",
        tutor : "repititor",
    },
    {
        apparent : "aniq, muqarrar",
        blind : "ko'r, ko'zi ojiz",
        calculate : "hisoblamoq",
        chat : "suhbatlashmoq",
        commit : "va'da bermoq",
        compose : "tuzmoq, yaratmoq",
        dormitory : "yotoqxona",
        exhaust : "holdan toydirmoq",
        greenhouse : "issiqxona",
        ignore : "e'tiborsiz qoldirmoq",
        obvious : "aniq, ravshan",
        physics : "fizika",
        porsion : "qism, bo'lak",
        remind : "eslatmoq",
        secretary : "kotib(a)",
        severe : "qattiq, jiddiy",
        talent : "iqtidor",
        thesis : "teziz",
        uniform : "forma",
        vision : "ko'rish qobilyati",
    }, 
    {
        absorb : "so'rmoq, shimmoq",
        boss : "xo'jayin",
        commitee : "qo'mita, komitet",
        contract : "shartnoma",
        crew : "brigada",
        devote : "bag'ishlamoq",
        dig : "kavlamoq",
        dine : "tushlik qilmoq",
        donate : "hadya qilmoq",
        double : "ikki hissa",
        elevate : "balandroqqa qo'ymoq",
        flavor : "ta'm, maza",
        foundation : "jamg'arma",
        generation : "avlod",
        handle : "band, tutqich",
        layer : "qatlam",
        mud : "loy",
        smooth : "tekis",
        soil : "tuproq",
        unique : "o'zgacha, g'ayrioddiy",
    }

 



]

